name: Deploy NixOS Configuration

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Deploy to NixOS Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
      run: |
        # Set up SSH key
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

        # Copy deploy script to server
        scp deploy_script.sh $SERVER_USER@$SERVER_IP:~/deploy_script.sh

        # SSH into server and run deploy script
        ssh $SERVER_USER@$SERVER_IP "bash ~/deploy_script.sh"

        # Clean up
        ssh $SERVER_USER@$SERVER_IP "rm ~/deploy_script.sh"
        rm -f ~/.ssh/id_rsa
