name: Deploy NixOS Configuration

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        run: |
          TEMP_SSH_DIR=$(mktemp -d)
          echo "$SSH_PRIVATE_KEY" > $TEMP_SSH_DIR/id_rsa
          chmod 600 $TEMP_SSH_DIR/id_rsa
          touch $TEMP_SSH_DIR/known_hosts
          cat << EOF > $TEMP_SSH_DIR/config
          StrictHostKeyChecking no
          UserKnownHostsFile $TEMP_SSH_DIR/known_hosts
          Port 22222
          EOF
          echo "TEMP_SSH_DIR=$TEMP_SSH_DIR" >> $GITHUB_ENV

      - name: Deploy to NixOS Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
        run: |
          # Ensure we're in the repository root
          cd $GITHUB_WORKSPACE

          # Copy deploy script to server
          scp -i $TEMP_SSH_DIR/id_rsa -F $TEMP_SSH_DIR/config \
            .github/workflows/deploy-script.sh $SERVER_USER@$SERVER_IP:~/deploy-script.sh

          # Run deploy script on server
          ssh -i $TEMP_SSH_DIR/id_rsa -F $TEMP_SSH_DIR/config \
            $SERVER_USER@$SERVER_IP "REPO_URL=$REPO_URL bash ~/deploy-script.sh"

          # Clean up
          ssh -i $TEMP_SSH_DIR/id_rsa -F $TEMP_SSH_DIR/config \
            $SERVER_USER@$SERVER_IP "rm ~/deploy-script.sh"

      - name: Clean up
        if: always()
        run: rm -rf $TEMP_SSH_DIR
