name: Deploy NixOS Configuration

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" > ~/.ssh/config

      - name: Deploy to NixOS Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
        run: |
          # Copy deploy script to server
          scp deploy_script.sh $SERVER_USER@$SERVER_IP:~/deploy_script.sh

          # Run deploy script on server
          ssh $SERVER_USER@$SERVER_IP "REPO_URL=$REPO_URL bash ~/deploy_script.sh"

          # Clean up
          ssh $SERVER_USER@$SERVER_IP "rm ~/deploy_script.sh"

      - name: Clean up
        if: always()
        run: rm -f ~/.ssh/id_rsa ~/.ssh/config
