name: Deploy NixOS Configuration

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        run: |
          TEMP_SSH_DIR=$(mktemp -d)
          echo "$SSH_PRIVATE_KEY" > $TEMP_SSH_DIR/id_rsa
          chmod 600 $TEMP_SSH_DIR/id_rsa
          echo "StrictHostKeyChecking no" > $TEMP_SSH_DIR/config
          echo "TEMP_SSH_DIR=$TEMP_SSH_DIR" >> $GITHUB_ENV

      - name: Deploy to NixOS Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
        run: |
          # Copy deploy script to server
          scp -i $TEMP_SSH_DIR/id_rsa -F $TEMP_SSH_DIR/config \
            deploy_script.sh $SERVER_USER@$SERVER_IP:~/deploy_script.sh

          # Run deploy script on server
          ssh -i $TEMP_SSH_DIR/id_rsa -F $TEMP_SSH_DIR/config \
            $SERVER_USER@$SERVER_IP "REPO_URL=$REPO_URL bash ~/deploy_script.sh"

          # Clean up
          ssh -i $TEMP_SSH_DIR/id_rsa -F $TEMP_SSH_DIR/config \
            $SERVER_USER@$SERVER_IP "rm ~/deploy_script.sh"

      - name: Clean up
        if: always()
        run: rm -rf $TEMP_SSH_DIR
