name: Deploy NixOS Configuration

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create temporary directory
        run: |
          TEMP_DIR=$(mktemp -d)
          echo "TEMP_DIR=$TEMP_DIR" >> $GITHUB_ENV

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p $TEMP_DIR/.ssh
          echo "$SSH_PRIVATE_KEY" > $TEMP_DIR/.ssh/id_rsa
          chmod 600 $TEMP_DIR/.ssh/id_rsa

      - name: Add server to known hosts
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: ssh-keyscan -H $SERVER_IP >> $TEMP_DIR/.ssh/known_hosts

      - name: Copy deploy script to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          scp -i $TEMP_DIR/.ssh/id_rsa -o UserKnownHostsFile=$TEMP_DIR/.ssh/known_hosts \
            deploy_script.sh $SERVER_USER@$SERVER_IP:~/deploy_script.sh

      - name: Run deploy script on server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
        run: |
          ssh -i $TEMP_DIR/.ssh/id_rsa -o UserKnownHostsFile=$TEMP_DIR/.ssh/known_hosts \
            $SERVER_USER@$SERVER_IP "REPO_URL=$REPO_URL bash ~/deploy_script.sh"

      - name: Clean up
        if: always()
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -i $TEMP_DIR/.ssh/id_rsa -o UserKnownHostsFile=$TEMP_DIR/.ssh/known_hosts \
            $SERVER_USER@$SERVER_IP "rm ~/deploy_script.sh"
          rm -rf $TEMP_DIR
